### ISSUE TITLE
Huge delay for deoplete popup + wrong behavior

### ISSUE THREAD

**Issue by vaxXxa** [zchee/deoplete-jedi#69]
* OS: macOS Sierra 10.12
 * Neovim version: NVIM 0.1.5

Config for `deoplete-jedi`:
```VimL
Plug 'zchee/deoplete-jedi', {'for': 'python'}
```

Problem: can't find methods, modules, etc. + delay for showing any deoplete popup > 5 seconds. If I disabled `deoplete-jedi` – everything works fine with deoplete, except that I can't use jedi features for deoplete.

**Comment by blueyed** [comment]
Please adhere to the issue template, e.g. in this case the debug log would be useful.

**Comment by zchee** [comment]
@vaxXxa Thanks for the issue.
I understand your problem, means deoplete.nvim works fine but very slow only the jedi source?

But, sorry. there is no information for the debug :(
Could you post a debug log, your edited file, or whatever information? (See issue template)

**Comment by vaxXxa** [comment]
@zchee sure, sorry for my bad issue description.

```log
2016-09-25 10:26:38,606 INFO     (deoplete.logging) --- Deoplete Log Start ---
2016-09-25 10:26:38,608 INFO     (deoplete.logging) NVIM 0.1.5, Python 3.6.0, neovim client 0.1.8
2016-09-25 10:26:50,720 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-09-25 10:26:50,721 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 67, in run
    self.out_queue.put(self.completion_work(*work), block=False)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, in completion_work
    filename)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 531, in completions
    stream_write(self._server.stdin, args)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 101, in stream_write
    pipe.flush()
BrokenPipeError: [Errno 32] Broken pipe
2016-09-25 10:26:50,728 DEBUG    (deoplete.jedi.cache) Input: "us"
2016-09-25 10:26:50,728 DEBUG    (deoplete.jedi) Key: ('c6e0e8a322d5e54e4f5a6d67e191954e', ('ajax_views', 'RegistrationView', 'post'), 'vars'), Refresh: True, Wait: True
2016-09-25 10:26:50,782 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-09-25 10:26:50,783 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 67, in run
    self.out_queue.put(self.completion_work(*work), block=False)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, in completion_work
    filename)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 531, in completions
    stream_write(self._server.stdin, args)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 100, in stream_write
    buffer.write(header + data)
BrokenPipeError: [Errno 32] Broken pipe
2016-09-25 10:26:52,737 INFO     (deoplete.jedi) [34mgather_candidates[m t = [36m2017.792652[mms, µ = 0, σ = 0)
2016-09-25 10:26:52,748 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-09-25 10:26:52,749 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 67, in run
    self.out_queue.put(self.completion_work(*work), block=False)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, in completion_work
    filename)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 531, in completions
    stream_write(self._server.stdin, args)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 101, in stream_write
    pipe.flush()
BrokenPipeError: [Errno 32] Broken pipe
2016-09-25 10:26:52,755 DEBUG    (deoplete.jedi.cache) Input: "use"
2016-09-25 10:26:52,755 DEBUG    (deoplete.jedi) Key: ('c6e0e8a322d5e54e4f5a6d67e191954e', ('ajax_views', 'RegistrationView', 'post'), 'vars'), Refresh: True, Wait: True
2016-09-25 10:26:52,801 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-09-25 10:26:52,801 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 67, in run
    self.out_queue.put(self.completion_work(*work), block=False)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, in completion_work
    filename)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 531, in completions
    stream_write(self._server.stdin, args)
  File "/Users/vaxxxa/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 100, in stream_write
    buffer.write(header + data)
BrokenPipeError: [Errno 32] Broken pipe
2016-09-25 10:26:54,766 INFO     (deoplete.jedi) [34mgather_candidates[m t = [36m2021.401115[mms, µ = 0, σ = 0)
```

**Comment by tweekmonster** [comment]
@vaxXxa The server isn't running.  Could you get a sample of the server's log?  It should be found at: `/tmp/jedi-server.log`.  The output of `:CheckHealth` would be helpful, too.

**Comment by blueyed** [comment]
I think that https://github.com/zchee/deoplete-jedi/pull/65 might help in this regard, too: at least to get more information.
@vaxXxa 
Can you try the branch from the PR after having added the requested information while on the master branch?

**Comment by vaxXxa** [comment]
Now deoplete-jedi works in one case, when I don't activate project virtualenv.
CheckHealth:

```
health#deoplete#check
================================================================================

## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, ' . 'try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
================================================================================

## Remote Plugins
  - SUCCESS: Up to date

## Python 2 provider
  - INFO: `g:python2_host_prog` is not set.  Searching for python in the environment.
  - INFO: Executable: /usr/bin/python
  - INFO: Python2 version: 2.7.10
  - INFO: python-neovim Version: 0.1.8
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/Users/vaxxxa/.virtualenvs/neovim3/bin/python"
  - INFO: Executable: /Users/vaxxxa/.virtualenvs/neovim3/bin/python
  - INFO: Python3 version: 3.6.0
  - INFO: python-neovim Version: 0.1.8
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - ERROR: Missing Neovim RubyGem
      - SUGGESTIONS:
        - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

CheckHealth, after I type `$ workon myenv`:

```
health#deoplete#check
================================================================================

## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, ' . 'try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
================================================================================

## Remote Plugins
  - SUCCESS: Up to date

## Python 2 provider
  - INFO: `g:python2_host_prog` is not set.  Searching for python in the environment.
  - INFO: There are multiple python executables found.  Set "g:python2_host_prog" to avoid surprises.
  - INFO: Executable: /Users/vaxxxa/.virtualenvs/myenv/bin/python
  - INFO: Other python executable: /usr/bin/python
  - WARNING: Got an unexpected version of Python. This could lead to confusing error messages.
  - INFO: Python2 version: 3.6.0
  - INFO: python-neovim Version: unable to find neovim version
  - ERROR: Neovim Python client is not installed.
      - SUGGESTIONS:
        - Error found was: unable to find neovim version
        - Use the command `$ pip2 install neovim`
  - SUCCESS: Latest Neovim Python client is installed: (unknown)

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/Users/vaxxxa/.virtualenvs/neovim3/bin/python"
  - WARNING: Your virtualenv is not set up optimally.
      - SUGGESTIONS:
        - Suggestion: Create a virtualenv specifically for Neovim and use "g:python3_host_prog".  This will avoid the need to install Neovim's Python client in each virtualenv.
  - INFO: Executable: /Users/vaxxxa/.virtualenvs/neovim3/bin/python
  - INFO: Python3 version: 3.6.0
  - INFO: python-neovim Version: unable to find neovim version
  - ERROR: Neovim Python client is not installed.
      - SUGGESTIONS:
        - Error found was: unable to find neovim version
        - Use the command `$ pip3 install neovim`
  - SUCCESS: Latest Neovim Python client is installed: (unknown)

## Ruby provider
  - ERROR: Missing Neovim RubyGem
      - SUGGESTIONS:
        - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

**Comment by vaxXxa** [comment]
Seems that this problem exists only with Python 3 (I use Python 3.6 + virtualenv).
If I use Python 2.7 for another project – everything works fine.

**Comment by vaxXxa** [comment]
@tweekmonster how can I get `/tmp/jedi-server.log`? Could you explain please.

**Comment by tweekmonster** [comment]
@vaxXxa It should just be created after you enable debugging with

```
call deoplete#custom#set('jedi', 'debug_enabled', 1)
```

But, I think I may have found a possible cause for the issue.  Could you post the full portion of the script that this problem occurs in?  Like a whole function or something?  I just want to be able to see the completion context.

**Comment by vaxXxa** [comment]
```VimL
call deoplete#custom#set('jedi', 'debug_enabled', 1)
```
doesn't work for me.. Don't see any log files in `/tmp/`.

Simple example, where I have this issue:

```Python
import json

json.
```

**Comment by tweekmonster** [comment]
> doesn't work for me.. Don't see any log files in /tmp/.

Oh...hmm, that could be an indication that the server isn't starting at all.  Do you have write permissions to `/tmp/`?  Could you change this line to point to where you know for sure you have write permissions: [server.py#L545](https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L545)

**Comment by Shougo** [comment]
@vaxXxa 

I think it is needed.

```vim
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
call deoplete#custom#set('jedi', 'debug_enabled', 1)
```

**Comment by tweekmonster** [comment]
@Shougo He posted his log earlier.  So I just assumed he had those enabled.

**Comment by vaxXxa** [comment]
BTW I use Python 3.6.0a4

**Comment by tweekmonster** [comment]
Sorry, I completely glossed over that.  Jedi doesn't support 3.5+:

```
Programming Language :: Python :: 2
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
Programming Language :: Python :: 3.2
Programming Language :: Python :: 3.3
Programming Language :: Python :: 3.4
```

But, I'd at least like to solve the mystery of why the server isn't starting for you.  I just tried using a `3.6.0b1` venv and the server starts fine, it just gives no completions.

**Comment by yevhen-m** [comment]
You mean deoplete-jedi does not work for python3.6?

**Comment by tweekmonster** [comment]
> You mean deoplete-jedi does not work for python3.6?

deoplete-jedi's source should run fine under 3.6 (I think).  But, that doesn't matter if these don't work with 3.6:

- https://github.com/neovim/python-client
- https://github.com/davidhalter/jedi

**Comment by yevhen-m** [comment]
@tweekmonster 
Both jedi and python-client work with python 3.6 for me, but deoplete-jedi breaks everything.

**Comment by yevhen-m** [comment]
For example ))):
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/friday/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 98, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/friday/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
[deoplete]     return func(self, *args, **kwargs)
[deoplete]   File "/Users/friday/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 116, in gather_candidates
[deoplete]     cache_key, extra_modules = cache.cache_context(buf.name, context, src)
[deoplete]   File "/Users/friday/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py", line 429, in cache_context
[deoplete]     parents = get_parents(source, line)
[deoplete]   File "/Users/friday/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py", line 268, in get_parents
[deoplete]     indent = len(source[start]) - len(source[start].lstrip())
[deoplete] IndexError: list index out of range
[deoplete] Could not get completions from: jedi.  Use :messages for error details.
```

**Comment by blueyed** [comment]
@yevhen-m 
Please create a new issue - the traceback is good information!
Do you have a test case to reproduce it?  Please provide it in the new issue then.  Thanks!

**Comment by tweekmonster** [comment]
@yevhen-m That's not an issue with 3.6.  The jedi submodule this plugin uses actually doesn't work in 3.6 (at least not for me), it's just deoplete-jedi is suppressing the errors.

That trace looks like an empty source is being fed to deoplete-jedi or it's not handling unicode correctly.  As @blueyed said, that warrants a new issue with a little more context.

**Comment by yevhen-m** [comment]
I can't reproduce it deliberately, errors just happen when I try to use deoplete-jedi with 3.6 python versions (or maybe I'm not skilled enough to do that). That's why I switched to deoplete + jedi completions for python source and this combo just works.

**Comment by ysolis** [comment]
uhm ... python 3.6 will be released in December 2016 ... according to https://www.python.org/dev/peps/pep-0494/#release-schedule

so i think that this bug must be closed because happens related to a python version that is not yet released.

**Comment by zchee** [comment]
Sorry all. still I have no time...

@ysolis Hmm...
Yeah, 3.6 still unstable.
> this bug must be closed because...

it meaning is close issue thread?
If so, and if that problems caused by 3.6, I think it is a good idea to we prepare it from now.
So, without close issue, I will debugging it if I have time.

Anyway, I don't understand yet these issues.
Please give me some times.

**Comment by vaxXxa** [comment]
You can close this issue, and reopen after few months again. Or can fix before release.
Anyway, I will make a video screencast for this bug.

**Comment by vaxXxa** [comment]
https://dl.dropboxusercontent.com/u/33889723/iterm2-vim-deoplete-python36.mp4

**Comment by vaxXxa** [comment]
@zchee any chance to fix that?

**Comment by zchee** [comment]
@vaxXxa Sorry for delay...
I will watch your mp4. thanks :)

**Comment by vaxXxa** [comment]
@zchee Please, try to fix that, cause native `jedi` suggestions feature isn't good. Your plugin is really cool, but just doesn't work with Python 3.6. Thnx, man!

**Comment by zchee** [comment]
@vaxXxa 
>  Your plugin is really cool

Just in case, this project(and all of OSS project) is not author achievement only :)
Me, [deoplete-jedi contributors](https://github.com/zchee/deoplete-jedi/graphs/contributors),  and the users who posted & reported the issue (you too).

Deal with the issue is sometimes hard work, but the "issue" is brought up(?) the project.
So, thanks for posted issue.
I'm really sorry I have no time for this issue now, but I certainly will check it.
Please wait a moment.

**Comment by Shougo** [comment]
@vaxXxa 
deoplete-jedi is Python plugin and you are Python programmer.
You have reproduce-able Python3.6 environment and you need the fix.

Open Source Theory:
If you really need the fix, you should fix it.

**Comment by vaxXxa** [comment]
@Shougo @zchee ok ok :) I've got it.

**Comment by vaxXxa** [comment]
Hi all. So, I've found the next bugs:

1) https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L534
```python
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1508, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: type object 'NullHandler' has no attribute 'level'
```

I've fixed that with delete line 28 `log.addHandler(logging.NullHandler)`

2) https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L537
```python
NameError: name 'time' is not defined
```

Fix: just `import time`

3) `[Errno 2] No such file or directory: '~/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/parser/grammar3.6.txt'`

Hotfix: Copy `~/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/parser/grammar3.5.txt'` to `~/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/parser/grammar3.6.txt'`

**Comment by Shougo** [comment]
Nice.

**Comment by tweekmonster** [comment]
@vaxXxa I fixed 1 and 2.  3 will be something you must do on your own since it's a submodule and we don't want to write our own files in it.

Is it alright if this issue is closed?  I've lost track of whether or not the original problem in this issue is "resolved".  It's fine if you open a new issue that's more specific.

**Comment by vaxXxa** [comment]
@tweekmonster sure. Thank you for your fixes. Please, close this issue.

**Comment by tweekmonster** [comment]
Thanks, we can still discuss the things here, but if something comes up specifically please create a separate issue.

@blueyed I think you're more familiar with Jedi than I am.  Does making a copy of `grammar3.5.txt` -> `grammar3.6.txt` actually work or is it just avoiding the exception?  Maybe a workaround will be for the server to make a temporary copy of the file if running 3.6 and delete it when the server shuts down.

**Comment by blueyed** [comment]
@tweekmonster 
I don't know.
A temporary copy sounds good.
We should check the Jedi issue tracker though.

**Comment by tweekmonster** [comment]
It's probably better to add the actual 3.6 grammar now that I'm thinking about it.  I couldn't find an issue related to the 3.6 grammar.  I started following the code in `jedi/parser/__init__.py` and stopped because I figured it might be faster to ask you.  😛
