### ISSUE TITLE
Error from failed script_completion is not reported

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#47]
# Problems summary

When Jedi throws an exception while generating completions, this is not properly reported.

Given the following code:

```
import requests
r = requests.get('www.github.com')
r.
```

Nothing happens when calling `deoplete#manual_complete` or when deoplete completes automatically (at the end).

An error shows up when enabling logging (`:call deoplete#enable_logging(100, '/tmp/deo.log')`):

```
2016-07-12 11:27:52,246 DEBUG    (deoplete.jedi.cache) Starting reaper thread
2016-07-12 11:27:52,248 DEBUG    (deoplete.jedi.cache) Input: "r."
2016-07-12 11:27:52,256 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-07-12 11:27:52,302 DEBUG    (deoplete.jedi.Thread-1) Completed work
2016-07-12 11:27:52,303 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-07-12 11:27:52,303 DEBUG    (deoplete.jedi.cache) Processed: ('boilerplate~',)
2016-07-12 11:27:52,609 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 67, in run
    self.out_queue.put(self.completion_work(*work), block=False)
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, in completion_work
    filename)
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 533, in completions
    return stream_read(self._server.stdout)
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 83, in stream_read
    raise StreamEmpty
deoplete_jedi.server.StreamEmpty
```

When enabling `--debug` for the server, the StreamEmpty exception is not logged anywhere anymore (?!), but this shows up in /tmp/jedi-server.log:

```
Input closed.  Shutting down.
Starting server.  sys.path = ['…/vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi', '/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi', '/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources', '…/pyenv/tmp-system-2YTclz/lib/python35.zip', '…/pyenv/tmp-system-2YTclz/lib/python3.5', '…/pyenv/tmp-system-2YTclz/lib/python3.5/plat-linux', '…/pyenv/tmp-system-2YTclz/lib/python3.5/lib-dynload', '/usr/lib64/python3.5', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '…/pyenv/tmp-system-2YTclz/lib/python3.5/site-packages']
Line: 1, Col: 0, Filename: ''
Line: 3, Col: 2, Filename: '…/Vcs/vim/t.py'
Failed completion 'script_completion'
```

When using `log.exception` there this traceback shows up - apparently an error with Jedi:

```
Traceback (most recent call last):
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 122, in wrapper
    return func(self, source, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi//rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 283, in script_completion
    completions = jedi.Script(source, line, col, filename).completions()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/api/__init__.py", line 254, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/api/__init__.py", line 298, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/iterable.py", line 229, in get_index_types
    types += self.get_exact_index_types(index.obj)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/iterable.py", line 255, in get_exact_index_types
    return self._evaluator.eval_element(self._items()[mixed_index])
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/iterable.py", line 575, in iter_content
    module = self.var_args.get_parent_until()
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/evaluate/param.py", line 56, in get_parent_until
    return element.get_parent_until(*args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/jedi/jedi/parser/tree.py", line 123, in get_parent_until
    while scope.parent is not None:
AttributeError: 'ListComprehension' object has no attribute 'parent'
```
## Expected
1. The exception should be logged in `retry_completion`.
2. The user should be informed about the error.

The completion works using `<C-X><C-O>`, but that uses another version of Jedi
(through jedi-vim).  So apparently the Jedi submodule should probably get
updated to fix this bug.
## Environment Information
- OS: Arch Linux
- Neovim version: v0.1.5-535-ge906111

**Comment by tweekmonster** [comment]
@blueyed Thanks.  We never got around to passing the debug log file to the server, which is why it uses `/tmp/server.log`.  Since it's in a separate process, we didn't want to tangle the messages in deoplete's logs.   `g:deoplete#sources#jedi#debug_enabled` also needs to be set to enable the server debugging.

> When enabling --debug for the server, the StreamEmpty exception is not logged anywhere anymore (?!), but this shows up in /tmp/jedi-server.log

Hmm, did you run the server directly?  If so, it expects data immediately or it shuts down (it's to avoid a deadlock).  The `StreamEmpty` exception you saw is happening on the client side, which is why it's in deoplete's logs.  It should only be raised on the server if the client doesn't send a header, which is confusing if that's the output from `log.exception()`.  I'll have to investigate.

> So apparently the Jedi submodule should probably get updated to fix this bug.

Thanks for the tip!  There were some issues with 0.9.0 that I can't remember now.  The server code might need to be updated to work with 0.10.0 though since we were using some workarounds.

**Comment by blueyed** [comment]
> Hmm, did you run the server directly? 

I've made the `self.cmd.append('--debug')` unconditional in `server.py`.. :)
That might also explain that something was not logged anymore, because debugging was not enabled properly?!

The issue about the error not being reported to the user in Neovim might be related to `DeopleteLogFilter` not being enabled without debug logging?  Its `filter` method is where it will eventually call `deoplete#util#print_error` for errors (https://github.com/Shougo/deoplete.nvim/blob/8102bbb73f942b232b6bcc00b8699fbe3b3f370c/rplugin/python3/deoplete/logger.py#L27-L39).

> The server code might need to be updated to work with 0.10.0 though since we were using some workarounds.

Just tried jedi's master and it seems to work as-is.

**Comment by tweekmonster** [comment]
> The issue about the error not being reported to the user in Neovim might be related to DeopleteLogFilter not being enabled without debug logging?

Ah okay, yeah.  That was by design, but I can see the flaw in it now.  There probably needs to be a different handler for `ERROR` and up messages if there's no log file.

> Just tried jedi's master and it seems to work as-is.

Confirmed it seems to work so far.  I want to take a little time with it to see if something else breaks.  It's been a while since I wrote the server and need to get my memory back.

> I wanted to create a PR and see how Travis reacts, but apparently there are no tests?

Yes there's no tests right now.  The ones that exist were from before the server was added.  We were trying to think through how to go about testing the server, but I got busy with work.

Side note: I also didn't notice that the submodule was a fork! 😯  And I could've sworn I saw a v0.10.0 tag for Jedi, but I guess I only saw the issue.

Incidentally this issue helped me hunt down a problem that was causing completions to suddenly become slow.  #48

**Comment by zchee** [comment]
@blueyed Thanks for issue and explain.
@tweekmonster send a pull request https://github.com/zchee/deoplete-jedi/pull/49, will merge soon.
Please try it after merge it if you have time.

**Comment by Shougo** [comment]
I have reproduced the error in the latest version.

**Comment by Shougo** [comment]
> I have reproduced the error in the latest version.

This is my fault.

@blueyed I cannot reproduce the error in the latest version.  Please test it again.

**Comment by Shougo** [comment]
@blueyed Ping.

**Comment by blueyed** [comment]
Closing for now.
